### ISSUE TITLE
Edited taxonomy title-tags won't become visible on website

### ISSUE THREAD

**Issue by Kristian1994** [wetpaintweb/seo-editor#3]
I have tried to update title tags across a number of taxonomies using your plugin, but find that the new title tag does not take effect when I subsequently visit the site, although it does take effect in the Yoast SEO plugin when I edit directly on the taxonomy page. Only when I edit the title tag and saving on the taxonomy page does the new title tag take effect. Therefore, updating meta data still requires manual handling, which I do not think makes sense?
Best regards 
Kristian

**Comment by matt-h** [comment]
Hi, since the recent Yoast plugin update which added indexing of the Titles and Meta we do not have a fix implemented yet in this plugin to fully work with that new feature. The actual data is still updating, but the cached indexes do not re-generate so it still shows the old data.

As a workaround for now, you can still update the tags with this plugin but then trigger Yoast to re-index everything to update it.

One way to trigger the re-index is to install the [Yoast Test Helper plugin](https://wordpress.org/plugins/yoast-test-helper/) and hit the button labeled "Reset Indexables tables & migrations" under "Tools" -> "Yoast Test". This will reset the Yoast Indexes, causing it to ask you to index the site.

**Comment by Kristian1994** [comment]
Hi Matt, thank you very much for sharing your workaround with me. It worked as intended.
